title: Jennifer Glaubius # your name (or website title) here
logo: "/images/libraryProfilePic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data scientist with experience wrangling and analyzing complex archaeological and geomorphic data sets. 
  <br><br>
  Geospatial analyst with 10+ years experience in GIS and image processing. 
  <br><br>
  <a href="www.linkedin.com/in/jen-glaubius">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-104343330-2 # your Google Analytics tracking ID here
